language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
env:
  - GO111MODULE=on BLESECRET=ci-secret BLE_CLIENT_ADDR=11:22:33:44:55:66 BLE_SERVER_ADDR=11:22:33:44:55:66 BLE_FORWARDER_ADDR=11:22:33:44:55:66
os:
  - linux
dist: trusty
sudo: false
install: true
script:
  - make
  - make -B test &> report.txt
  - cat report.txt
  - scripts/check_cov.sh