language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on BLESECRET=cisecret make
  - env GO111MODULE=on make -B test